language: go
go:
  - 1.2
install:
  - go get -v code.google.com/p/go.tools/cmd/vet
  - go get -v github.com/tools/godep
  - go get -v github.com/onsi/ginkgo/ginkgo
  - PATH=$PATH:$HOME/gopath/bin bin/generate-language-resources
  - go get -v -t ./...
script:  bin/travis
branches:
  only:
  - master
