language: go
go:
  - 1.3.1
install:
  - go get -v code.google.com/p/go.tools/cmd/vet
  - go get -v github.com/tools/godep
  - go get -v github.com/onsi/ginkgo/ginkgo
script:  bin/test
branches:
  only:
  - master
