language: go
go:
- 1.2
before_install:
- go get code.google.com/p/go.tools/cmd/vet
- go get github.com/tools/godep
install: PATH=$PATH:$HOME/gopath/bin ./bin/build
script:  PATH=$PATH:$HOME/gopath/bin ./bin/test
branches:
  only:
  - master
