---
platform: windows

params:
  ADMIN_USER:
  ADMIN_PASSWORD:

inputs:
- name: cf-acceptance-tests
  path: gopath/src/github.com/cloudfoundry/cf-acceptance-tests
- name: cf-cli-binaries
- name: ci
- name: bosh-lite-lock

run:
  path: ci/concourse/builds/cats-windows.bat
