---
platform: linux
image: docker:///cloudfoundry/cli-ci

inputs:
- name: cross-compiled
- name: osx-compiled

outputs:
- name: compiled

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cwd=$PWD

    mkdir combined

    pushd cross-compiled
      tar -xzf *.tgz
      rm *.tgz
      mv * $cwd/compiled
    popd

    pushd osx-compiled
      tar -xzf *.tgz
      rm *.tgz
      mv * $cwd/compiled
    popd

    tar -cvzf $cwd/compiled/cf-cli-binaries.tgz -C compiled .
