---
platform: windows

params:
  SIGNTOOL_CERT_PATH:
  SIGNTOOL_CERT_PASSWORD:

inputs:
- name: cf-cli-binaries
- name: cli

outputs:
- name: winstallers

run:
  path: cli/ci/tasks/create-installers-windows.bat
