---
platform: linux

image: docker:///cloudfoundry/cli-vagrant-ci

params:
  LITE_PRIVATE_IP_ADDRESS:
  LITE_HOSTNAME:

inputs:
- name: cf-routing-release-repo
- name: cf-release-repo

run:
  path: bash
  args:
  - -c
  - |
    set -eux

    export DOMAIN=`cat bosh-lite-lock/name`

    export ADMIN_USER=admin
    export ADMIN_PASSWORD=admin
    export API_ENDPOINT="https://api.${DOMAIN}"

    cf_deployment_name=cf-warden
    cf_deployment_file=cf-warden.yml

    diego_deployment_name=cf-warden-diego
    diego_deployment_file=cf-warden-diego.yml

    ####
    # DELETEME
    # ROUTING RELEASE COMPILATION ISSUE: https://www.pivotaltracker.com/story/show/115208829
    routing_deployment_file=cf-warden-routing.yml
    ####

    bosh -n target $LITE_PRIVATE_IP_ADDRESS

    ####
    # DELETEME
    # ROUTING RELEASE COMPILATION ISSUE: https://www.pivotaltracker.com/story/show/115208829
    cat<<EOF > cf-routing-release-repo/worker-overrides.yml
    compilation:
      workers: 2
    EOF
    ####

    ####
    # DELETEME
    # UAA SSL ISSUE: https://www.pivotaltracker.com/story/show/115208829
    # Taken from https://github.com/cloudfoundry/cf-release/blob/25ffce828e9be94ab62b71659f75e128fc5e4b48/templates/cf-infrastructure-warden.yml#L94-L149
    cat<<EOF > cf-routing-release-repo/uaa-ssl-overrides.yml
    properties:
      uaa:
        ssl:
          port: 8443
        sslCertificate: |
          -----BEGIN CERTIFICATE-----
          MIIEJzCCAw+gAwIBAgIJAKcbTg/7imgFMA0GCSqGSIb3DQEBBQUAMGoxCzAJBgNV
          BAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQKEw1DbG91ZCBGb3Vu
          ZHJ5MQwwCgYDVQQLEwNVQUExIDAeBgNVBAMTF3VhYS5zZXJ2aWNlLmNmLmludGVy
          bmFsMB4XDTE2MDIyNjE4NDcwM1oXDTI2MDIyMzE4NDcwM1owajELMAkGA1UEBhMC
          VVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAoTDUNsb3VkIEZvdW5kcnkx
          DDAKBgNVBAsTA1VBQTEgMB4GA1UEAxMXdWFhLnNlcnZpY2UuY2YuaW50ZXJuYWww
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC1ePY4cEfqPCX8IObvlCtv
          mWQW00hzJ2GiGRT/4cuCCppn7O04Io2GWR8HiIEtqNqMmPfglzT4tuNeUzsgTBfF
          /w3sdF4HwlRXHoAHXbFpZlfe057q5IKdzDy6yqY4mDVwzLUtof9PwcZ8U7Jm3j3A
          yXozeRiXE4pevprMLCjq+AXmOHSMxUC6K3haR3pAsmgPioanViLC1TsLdOQ1E9z+
          lirjiYYFUBep/y6mNuVdEbHdmMRFmmVIldtB9R8vlUa04b7ghnWX1wyZRD1WpucB
          cV9hoeIwgTVBrHRro4jnobOmK36pmlc2HpFaLtb0didZveO2oxN4i3oW/rwOP0of
          AgMBAAGjgc8wgcwwHQYDVR0OBBYEFCavF5V4kxQ/8g3H29qWkVUbQ/u6MIGcBgNV
          HSMEgZQwgZGAFCavF5V4kxQ/8g3H29qWkVUbQ/u6oW6kbDBqMQswCQYDVQQGEwJV
          UzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEChMNQ2xvdWQgRm91bmRyeTEM
          MAoGA1UECxMDVUFBMSAwHgYDVQQDExd1YWEuc2VydmljZS5jZi5pbnRlcm5hbIIJ
          AKcbTg/7imgFMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBALJQDlKt
          j0BZEYsuS7RSFMWRQjol0Z4tQnUoOquiBD3bL4RVxBHYFZZ6rufwxKPsRHbduUO8
          d7y3ar8iOU/3IeXWFTFgjjTU3gqD15rUckeH4NTNExxbRLWStbEaxn6uL35To6zx
          surB3v0bMY3w1fwHbWwAQ+Fw8y/izLxcv61uTJXlQjjBcNnXlqKBnfB8HjjfWppb
          O6k1jA9cUA69vIxN0KqxunSCrNmJWCwDPx22bX1oCyhaqUtLyOHuEA4Q8VNEj6Nh
          a/V0gzk7kVKnBRwgY50xrEQhw0r6CCeydy2hthmrcWpujaEapymfv0lHvDiyA8sL
          m99p7wzkO1EuAz8=
          -----END CERTIFICATE-----
        sslPrivateKey: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEogIBAAKCAQEAtXj2OHBH6jwl/CDm75Qrb5lkFtNIcydhohkU/+HLggqaZ+zt
          OCKNhlkfB4iBLajajJj34Jc0+LbjXlM7IEwXxf8N7HReB8JUVx6AB12xaWZX3tOe
          6uSCncw8usqmOJg1cMy1LaH/T8HGfFOyZt49wMl6M3kYlxOKXr6azCwo6vgF5jh0
          jMVAuit4Wkd6QLJoD4qGp1YiwtU7C3TkNRPc/pYq44mGBVAXqf8upjblXRGx3ZjE
          RZplSJXbQfUfL5VGtOG+4IZ1l9cMmUQ9VqbnAXFfYaHiMIE1Qax0a6OI56Gzpit+
          qZpXNh6RWi7W9HYnWb3jtqMTeIt6Fv68Dj9KHwIDAQABAoIBAF3lptDxF+TVFnps
          s9FHA2qNHcLJs/URbW0oOTtlI523ysj3SI8BIeVf+7Q0J1LuyZZyF9/3nQsL5n2J
          51AAz1Q9coDkfTrajDU/rNMi4Yc90z2SlenILuVjJhEohfVGnHAvG5fu+GHWS9NM
          o0SivaUhGr/DarvQ+omnagU23D0nFKfrS1FC78cxoJKgKJbOVOWMZvAKlFHTv4z1
          3oozzOobJRE9qWmtBoWiWCLVmiXchpj8nOu8R/ybmJksBsmbERZPXnFIpUQVV3Ll
          TGaeIviboJXQx7MmolbH+61k9rgdpNvUgR/MP/jxtcKUOJVxnTCjITW5YAHR/az+
          8UAC8SECgYEA5o0xoWVQG9yb/lrO7txCHotILsZjk9BTucCIdh7nJutSVaNikRcy
          M6/TwCjRUeFghgspWrvY01L2cP38LU0lqjiwzs0Jhxs+lFkpihU3KivgrWtUY5Vx
          OHmy2TW+kodIZJUyY+mHYgI3fKiIByR5rM9LHp6vvw9MQ9GICB2u0UkCgYEAyYDr
          BMO6aM8diveRlY/HwbgRgpb/TI4JuyVY19aH2qzo6hGkc/YV6rit/hnDB7uZpM/z
          Kj3I+H0Xm4MQyUGmaiaEZfKMoVONb6CQmM2cDkGjSbGu+duP3Ol6EDc7u/svKSg+
          v32snrU2Cs1T7PxgDOgWrvuD232w0bDbUcKaKCcCgYBl5T9rKqDWP5F+QFo2/YgH
          gd18NthpyuhGL47gTdYxwE2aZeS5ZXwdlfdLdX7V5ntHowU7AczZ0U/0LnzW9MLR
          0c5rB/nPCb6FyEZwreG8tLnPS6F3heQNZtQh5fv9POdE9R/ZQqxAJ+SoJsBAD+Hq
          +48i0FWyZqt5SdEKbTwHaQKBgDyOKJKq+2cp7vfnRHIM3nwiA+kZ1ak8+kGqjJN4
          niUiV3CYUrKinp2GWIuHVGwLfbXg5HOqU64RcbnDXpUMzKUT5C/6/zYwNM36E9pH
          2AEUyqyH4EyoJgi+hXdAEgyBBQA6XvkPHIQpcw81+2W5xme6i66UWWDp2ex6WL6u
          W8N7AoGAWuxpDX9MawvJ5j62u19o9giJ9bSq/KwJ/cAEJql+V9c3d9RZenS90OTV
          HzneT3ZbOcsEIvK14FecXzV7OqRvOePXSJ2cS8lNqd1k2pxCjliYW4pfQm7e58ma
          /6wtWeX8QMBcZ6ufxs0VgxPv4P8jczrzqxgszLUK8hdnZEL7+xk=
          -----END RSA PRIVATE KEY-----
    EOF
    ####

    pushd cf-routing-release-repo
      bosh -n -u $ADMIN_USER -p $ADMIN_PASSWORD create release --force
      bosh -n -u $ADMIN_USER -p $ADMIN_PASSWORD upload release --rebase

      bosh -n -u $ADMIN_USER -p $ADMIN_PASSWORD download manifest $cf_deployment_name $cf_deployment_file
      bosh -n -u $ADMIN_USER -p $ADMIN_PASSWORD download manifest $diego_deployment_name $diego_deployment_file

      ####
      # DELETEME
      # UAA SSL ISSUE: https://www.pivotaltracker.com/story/show/115208829
      spiff merge $cf_deployment_file uaa-ssl-overrides.yml > cf-warden-uaa-fix.yml
      bosh -n -u $ADMIN_USER -p $ADMIN_PASSWORD deployment cf-warden-uaa-fix.yml
      bosh -n -u $ADMIN_USER -p $ADMIN_PASSWORD deploy
      ####

      ./scripts/generate-bosh-lite-manifest $cf_deployment_file $diego_deployment_file

      ####
      # DELETEME
      # ROUTING RELEASE COMPILATION ISSUE: https://www.pivotaltracker.com/story/show/115208829
      spiff merge ./bosh-lite/deployments/cf-routing-manifest.yml worker-overrides.yml > $routing_deployment_file
      bosh -n -u $ADMIN_USER -p $ADMIN_PASSWORD deployment $routing_deployment_file
      ####

      bosh -n -u $ADMIN_USER -p $ADMIN_PASSWORD deploy
    popd


    cat<<EOF > cf-release-repo/property-overrides.yml
    properties:
      cc:
        default_to_diego_backend: true
      router:
        enable_routing_api: true
      domain: $LITE_HOSTNAME
    EOF

    pushd cf-release-repo
      ./scripts/generate-bosh-lite-dev-manifest property-overrides.yml
      bosh -n -u $ADMIN_USER -p $ADMIN_PASSWORD deploy
    popd

    bosh -n -u $ADMIN_USER -p $ADMIN_PASSWORD cleanup