---
platform: linux

image: docker:///cloudfoundry/cli-vagrant-ci

params:
  LITE_PRIVATE_IP_ADDRESS:

inputs:
- name: cli-pools
- name: etcd-release
- name: garden-linux-release
- name: diego-release
- name: diego-repo
- name: cflinuxfs2-rootfs-release

run:
  path: bash
  args:
  - -c
  - |
    set -eux

    bosh -n target $LITE_PRIVATE_IP_ADDRESS
    bosh login admin admin
    bosh upload release cflinuxfs2-rootfs-release/release.tgz --skip-if-exists
    bosh upload release etcd-release/release.tgz --skip-if-exists
    bosh upload release garden-linux-release/release.tgz --skip-if-exists
    bosh upload release diego-release/release.tgz --skip-if-exists

    mkdir -p cf-warden
    export CF_MANIFESTS_DIR=$PWD/cf-warden
    bosh download manifest cf-warden $CF_MANIFESTS_DIR/cf.yml

    pushd diego-repo
      ./scripts/generate-bosh-lite-manifests
    popd

    bosh deployment diego-repo/bosh-lite/deployments/diego.yml
    bosh -n deploy

    export DOMAIN=`cat cli-pools/name`

    curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar -zx
    ./cf api "https://api.${DOMAIN}" --skip-ssl-validation
    ./cf auth admin admin
    # This feature flag only affects the diego acceptance tests
    ./cf enable-feature-flag diego_docker

