---
platform: linux

image: docker:///cloudfoundry/cli-vagrant-ci

params:
  LITE_PRIVATE_IP_ADDRESS:

inputs:
- name: etcd-release
- name: garden-linux-release
- name: diego-release
- name: diego-repo

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    bosh -n target $LITE_PRIVATE_IP_ADDRESS
    bosh -n -u admin -p admin upload release etcd-release/release.tgz
    bosh -n -u admin -p admin upload release garden-linux-release/release.tgz
    bosh -n -u admin -p admin upload release diego-release/release.tgz

