---
platform: linux

image: docker:///cloudfoundry/cli-vagrant-ci

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  LITE_KEYPAIR:
  LITE_PRIVATE_KEY_PATH:
  AWS_SECURITY_GROUP:
  AWS_SUBNET_ID:
  LITE_NAME:
  LITE_PRIVATE_IP_ADDRESS:
  LITE_HOSTNAME:

inputs:
  - name: cli-private
  - name: bosh-lite
  - name: cf-release-repo

outputs:
  - name: provision-cf-lite

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export BOSH_AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
    export BOSH_AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
    export BOSH_LITE_KEYPAIR="${LITE_KEYPAIR}"
    export BOSH_LITE_PRIVATE_KEY=$PWD/"${LITE_PRIVATE_KEY_PATH}"
    export BOSH_LITE_SECURITY_GROUP="${AWS_SECURITY_GROUP}"
    export BOSH_LITE_SUBNET_ID="${AWS_SUBNET_ID}"
    export BOSH_LITE_NAME="${LITE_NAME}"
    export BOSH_LITE_ROOT="$PWD/bosh-lite"
    export SCRATCH_ROOT="$PWD/scratch"

    mkdir scratch

    pushd scratch
      vagrant init cloudfoundry/bosh-lite

      sed -i -e "s/do |config|/do |config|\n  config.vm.provider 'aws' do |aws|\n    aws.instance_type = 'm3.2xlarge'\n    aws.private_ip_address = '${LITE_PRIVATE_IP_ADDRESS}'\n  end/" \
        Vagrantfile

      vagrant up --provider aws
    popd

    pushd cf-release-repo
      sleep 30

      bosh -n target $LITE_PRIVATE_IP_ADDRESS
      bosh -n login admin admin

      echo "Updating cf-release sub modules"
      ./scripts/update > /dev/null

      echo "Generating bosh lite manifest from cf-release-repo/scripts/generate-bosh-lite-dev-manifest"
      cat > property-overrides.yml << EOF
    properties:
      domain: ${LITE_HOSTNAME}
    EOF
      ./scripts/generate-bosh-lite-dev-manifest property-overrides.yml
    popd

    mkdir -p provision-cf-lite
    cp cf-release-repo/bosh-lite/deployments/cf.yml provision-cf-lite
