---
platform: linux

image: docker:///cloudfoundry/cli-vagrant-ci

params:
  LITE_PRIVATE_IP_ADDRESS:

inputs:
- name: bosh-lite-lock

run:
  path: bash
  args:
  - -c
  - |
    set -eux

    export DOMAIN=`cat bosh-lite-lock/name`

    export ADMIN_USER=admin
    export ADMIN_PASSWORD=admin
    export API_ENDPOINT="https://api.${DOMAIN}"

    bosh -n target $LITE_PRIVATE_IP_ADDRESS
    bosh login $ADMIN_USER $ADMIN_PASSWORD
    bosh -n download manifest 'cf-warden' cf-warden.yml
    bosh -n deployment cf-warden.yml
    bosh -n run errand smoke_tests
