---
platform: darwin

image: docker:///cloudfoundry/cli-ci

params:
  CERT_COMMON_NAME:
  CERT_LOCATION:
  CERT_PASSWORD_LOCATION:

inputs:
- name: certificates
- name: cli-ci
- name: edge-osx-installer-64

outputs:
- name: signed-osx-installer

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    VERSION=$(cat cli-ci/ci/VERSION)
    CERT_PASSWORD=$(cat certificates/$CERT_PASSWORD_LOCATION)

    security create-keychain -p "" temp-keychain
    security import certificates/$CERT_LOCATION -k temp-keychain -T "$(which productsign)" -P "$CERT_PASSWORD"
    productsign --timestamp --sign "$CERT_COMMON_NAME" edge-osx-installer-64/cf-cli-installer_edge_osx.pkg signed-osx-installer/cf-cli-installer_$VERSION_osx.pkg --keychain $PWD/temp-keychain
    security delete-keychain temp-keychain
