---
resources:
- name: bosh-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-lite
    branch: master

- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: bosh-lite-acceptance-deploy-cf
  type: bosh-deployment
  source:
    target: {{lite-acceptance-public-ip}}
    username: admin
    password: admin
    deployment: cf-warden

- name: bosh-lite-1-deploy-cf
  type: bosh-deployment
  source:
    target: {{lite-1-public-ip-address}}
    username: admin
    password: admin
    deployment: cf-warden

- name: bosh-lite-2-deploy-cf
  type: bosh-deployment
  source:
    target: {{lite-2-public-ip-address}}
    username: admin
    password: admin
    deployment: cf-warden

- name: bosh-lites-acceptance-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: {{cli-pools-github-private-key}}
    branch: master
    pool: bosh-lites-acceptance

- name: bosh-lites-dea-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: {{cli-pools-github-private-key}}
    branch: master
    pool: bosh-lites-dea

- name: cf-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-release

- name: cf-release-repo
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: master

- name: cf-routing-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/cf-routing-release

- name: cf-routing-release-repo
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/cf-routing-release.git
    branch: master

- name: grootfs-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/grootfs-release

- name: cflinuxfs2-rootfs-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cflinuxfs2-rootfs-release

- name: cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths:
    - ci

- name: diego-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/diego-release

- name: diego-repo
  type: git
  source:
    uri: https://github.com/cloudfoundry/diego-release.git
    branch: master

- name: garden-runc-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release

- name: cf-networking
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/cf-networking-release

groups:
- name: bosh-lites
  jobs:
  - provision-bosh-lite-1
  - deploy-cf-release-1
  - smoke-test-1
  - deploy-diego-release-1
  - deploy-routing-release-1
  - provision-bosh-lite-2
  - deploy-cf-release-2
  - smoke-test-2
  - deploy-diego-release-2
  - deploy-routing-release-2
- name: dies-lite
  jobs:
  - provision-bosh-lite
  - deploy-cf-release
  - smoke-test
  - deploy-diego-release
  - deploy-routing-release

jobs:
- name: provision-bosh-lite-1
  serial: true
  plan:
  - aggregate:
    - get: bosh-lite
    - get: cli
    - put: bosh-lites-dea-pool
      params:
        claim: {{lite-1-hostname}}
  - do:
    - task: destroy
      file: cli/ci/infrastructure/tasks/destroy-cf-lite.yml
      params:
        AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
        AWS_REGION: {{lite-aws-region}}
        LITE_INSTANCE_NAME: bosh-lite-1
    - task: provision
      file: cli/ci/infrastructure/tasks/provision-cf-lite.yml
      privileged: true
      params:
        BOSH_LITE_NAME: bosh-lite-1
        BOSH_AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
        BOSH_LITE_ELASTIC_IP: {{lite-1-public-ip-address}}
        BOSH_LITE_KEYPAIR: {{lite-keypair}}
        BOSH_LITE_SECURITY_GROUP: {{lite-aws-security-group}}
        BOSH_LITE_SUBNET_ID: {{bosh-lite-subnet}}
        LITE_PRIVATE_KEY: {{bosh-lite-private-key}}

- name: deploy-cf-release-1
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-dea-pool
      passed: [provision-bosh-lite-1]
      trigger: true
    - get: cli
    - get: cf-release-repo
    - get: cf-release
    - get: bosh-lite-stemcell
  - do:
    - task: create-cf-manifest
      file: cli/ci/infrastructure/tasks/create-bosh-lite-cf-manifest.yml
      params:
        LITE_IP_ADDRESS: {{lite-1-public-ip-address}}
        LITE_HOSTNAME: {{lite-1-hostname}}
        LITE_EXTRA_STUB: 'properties: { dea_next : { memory_mb : 20480 } }'
    - put: bosh-lite-1-deploy-cf
      params:
        manifest: bosh-lite-cf-manifest/cf.yml
        stemcells:
          - bosh-lite-stemcell/stemcell.tgz
        releases:
          - cf-release/release.tgz

- name: smoke-test-1
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-dea-pool
      passed: [deploy-cf-release-1]
      trigger: true
    - get: cli
  - task: run-smoke-tests
    file: cli/ci/infrastructure/tasks/run-smoke-tests.yml
    params:
      LITE_IP_ADDRESS: {{lite-1-public-ip-address}}

- name: deploy-diego-release-1
  serial: true
  plan:
  - aggregate:
    - get: bosh-lite-lock
      resource: bosh-lites-dea-pool
      passed: [smoke-test-1]
      trigger: true
    - get: garden-runc-release
    - get: diego-release
    - get: diego-repo
    - get: cflinuxfs2-rootfs-release
    - get: cf-networking
    - get: cli
    - get: grootfs-release
  - task: deploy-diego
    file: cli/ci/infrastructure/tasks/deploy-diego.yml
    params:
      LITE_IP_ADDRESS: {{lite-1-public-ip-address}}

- name: deploy-routing-release-1
  serial: true
  plan:
  - aggregate:
    - get: bosh-lite-lock
      resource: bosh-lites-dea-pool
      passed: [deploy-diego-release-1]
      trigger: true
    - get: cf-routing-release
    - get: cf-routing-release-repo
    - get: cf-release-repo
    - get: cli
  - task: deploy-routing
    file: cli/ci/infrastructure/tasks/deploy-routing.yml
    params:
      LITE_IP_ADDRESS: {{lite-1-public-ip-address}}
      LITE_HOSTNAME: {{lite-1-hostname}}
  - task: test-routing
    file: cli/ci/infrastructure/tasks/test-routing.yml
    params:
      LITE_IP_ADDRESS: {{lite-1-public-ip-address}}
  - put: bosh-lites-dea-pool
    params:
      release: bosh-lite-lock

- name: provision-bosh-lite-2
  serial: true
  plan:
  - aggregate:
    - get: bosh-lite
    - get: cli
    - put: bosh-lites-dea-pool
      params:
        claim: {{lite-2-hostname}}
  - do:
    - task: destroy
      file: cli/ci/infrastructure/tasks/destroy-cf-lite.yml
      params:
        AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
        AWS_REGION: {{lite-aws-region}}
        LITE_INSTANCE_NAME: bosh-lite-2
    - task: provision
      file: cli/ci/infrastructure/tasks/provision-cf-lite.yml
      privileged: true
      params:
        BOSH_LITE_NAME: bosh-lite-2
        BOSH_AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
        BOSH_LITE_ELASTIC_IP: {{lite-2-public-ip-address}}
        BOSH_LITE_KEYPAIR: {{lite-keypair}}
        BOSH_LITE_SECURITY_GROUP: {{lite-aws-security-group}}
        BOSH_LITE_SUBNET_ID: {{bosh-lite-subnet}}
        LITE_PRIVATE_KEY: {{bosh-lite-private-key}}

- name: deploy-cf-release-2
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-dea-pool
      passed: [provision-bosh-lite-2]
      trigger: true
    - get: cli
    - get: cf-release-repo
    - get: cf-release
    - get: bosh-lite-stemcell
  - do:
    - task: create-cf-manifest
      file: cli/ci/infrastructure/tasks/create-bosh-lite-cf-manifest.yml
      params:
        LITE_IP_ADDRESS: {{lite-2-public-ip-address}}
        LITE_HOSTNAME: {{lite-2-hostname}}
        LITE_EXTRA_STUB: 'properties: { dea_next : { memory_mb : 20480 } }'
    - put: bosh-lite-2-deploy-cf
      params:
        manifest: bosh-lite-cf-manifest/cf.yml
        stemcells:
          - bosh-lite-stemcell/stemcell.tgz
        releases:
          - cf-release/release.tgz

- name: smoke-test-2
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-dea-pool
      passed: [deploy-cf-release-2]
      trigger: true
    - get: cli
  - task: run-smoke-tests
    file: cli/ci/infrastructure/tasks/run-smoke-tests.yml
    params:
      LITE_IP_ADDRESS: {{lite-2-public-ip-address}}

- name: deploy-diego-release-2
  serial: true
  plan:
  - aggregate:
    - get: bosh-lite-lock
      resource: bosh-lites-dea-pool
      passed: [smoke-test-2]
      trigger: true
    - get: garden-runc-release
    - get: diego-release
    - get: diego-repo
    - get: cflinuxfs2-rootfs-release
    - get: cf-networking
    - get: cli
    - get: grootfs-release
  - task: deploy-diego
    file: cli/ci/infrastructure/tasks/deploy-diego.yml
    params:
      LITE_IP_ADDRESS: {{lite-2-public-ip-address}}
  # - task: default-to-diego
  #   file: cli/ci/infrastructure/tasks/set-cf-backend-to-diego.yml
  #   params:
  #     LITE_IP_ADDRESS: {{lite-2-public-ip-address}}

- name: deploy-routing-release-2
  serial: true
  plan:
  - aggregate:
    - get: bosh-lite-lock
      resource: bosh-lites-dea-pool
      passed: [deploy-diego-release-2]
      trigger: true
    - get: cf-routing-release
    - get: cf-routing-release-repo
    - get: cf-release-repo
    - get: cli
  - task: deploy-routing
    file: cli/ci/infrastructure/tasks/deploy-routing.yml
    params:
      LITE_IP_ADDRESS: {{lite-2-public-ip-address}}
      LITE_HOSTNAME: {{lite-2-hostname}}
  - task: test-routing
    file: cli/ci/infrastructure/tasks/test-routing.yml
    params:
      LITE_IP_ADDRESS: {{lite-2-public-ip-address}}
  - put: bosh-lites-dea-pool
    params:
      release: bosh-lite-lock

- name: provision-bosh-lite
  serial: true
  plan:
  - aggregate:
    - get: bosh-lite
    - get: cli
    - put: bosh-lites-acceptance-pool
      params:
        claim: {{lite-acceptance-hostname}}
  - do:
    - task: destroy
      file: cli/ci/infrastructure/tasks/destroy-cf-lite.yml
      params:
        AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
        AWS_REGION: {{lite-aws-region}}
        LITE_INSTANCE_NAME: {{lite-acceptance-name}}
    - task: provision
      file: cli/ci/infrastructure/tasks/provision-cf-lite.yml
      privileged: true
      params:
        BOSH_LITE_NAME: {{lite-acceptance-name}}
        BOSH_AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
        BOSH_LITE_ELASTIC_IP: {{lite-acceptance-public-ip}}
        BOSH_LITE_KEYPAIR: {{acceptance-keypair}}
        BOSH_LITE_SECURITY_GROUP: {{lite-acceptance-security-group}}
        BOSH_LITE_SUBNET_ID: {{lite-acceptance-subnet-id}}
        LITE_PRIVATE_KEY: {{dies-lite-private-key}}

- name: deploy-cf-release
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-acceptance-pool
      passed: [provision-bosh-lite]
      trigger: true
    - get: cli
    - get: cf-release-repo
    - get: cf-release
    - get: bosh-lite-stemcell
  - task: create-cf-manifest
    file: cli/ci/infrastructure/tasks/create-bosh-lite-cf-manifest.yml
    params:
      LITE_IP_ADDRESS: {{lite-acceptance-public-ip}}
      LITE_HOSTNAME: {{lite-acceptance-hostname}}
      LITE_EXTRA_STUB: "properties: { doppler: { port: 443 } }"
  - put: bosh-lite-acceptance-deploy-cf
    params:
      manifest: bosh-lite-cf-manifest/cf.yml
      stemcells:
        - bosh-lite-stemcell/stemcell.tgz
      releases:
        - cf-release/release.tgz

- name: smoke-test
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-acceptance-pool
      passed: [deploy-cf-release]
      trigger: true
    - get: cli
  - task: run-smoke-tests
    file: cli/ci/infrastructure/tasks/run-smoke-tests.yml
    params:
      LITE_IP_ADDRESS: {{lite-acceptance-public-ip}}

- name: deploy-diego-release
  serial: true
  plan:
  - aggregate:
    - get: bosh-lite-lock
      resource: bosh-lites-acceptance-pool
      passed: [smoke-test]
      trigger: true
    - get: garden-runc-release
    - get: diego-release
    - get: diego-repo
    - get: cflinuxfs2-rootfs-release
    - get: cf-networking
    - get: cli
    - get: grootfs-release
  - do:
    - task: deploy-diego
      file: cli/ci/infrastructure/tasks/deploy-diego.yml
      params:
        LITE_IP_ADDRESS: {{lite-acceptance-public-ip}}
    - task: default-to-diego
      file: cli/ci/infrastructure/tasks/set-cf-backend-to-diego.yml
      params:
        LITE_IP_ADDRESS: {{lite-acceptance-public-ip}}

- name: deploy-routing-release
  serial: true
  plan:
  - aggregate:
    - get: bosh-lite-lock
      resource: bosh-lites-acceptance-pool
      passed: [deploy-diego-release]
      trigger: true
    - get: cf-routing-release
    - get: cf-routing-release-repo
    - get: cf-release-repo
    - get: cli
  - task: deploy-routing
    file: cli/ci/infrastructure/tasks/deploy-routing.yml
    params:
      LITE_IP_ADDRESS: {{lite-acceptance-public-ip}}
      LITE_HOSTNAME: {{lite-acceptance-hostname}}
  - task: test-routing
    file: cli/ci/infrastructure/tasks/test-routing.yml
    params:
      LITE_IP_ADDRESS: {{lite-acceptance-public-ip}}
  - put: bosh-lites-acceptance-pool
    params:
      release: bosh-lite-lock
