---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

outputs:
- name: vars_path

run:
  path: sh
  args:
  - -c
  - |
    set -eux

    cat << EOF > vars_path/vars.yml
    client_secret: ((client_secret))
    EOF
