---
resources:
- name: bosh-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-lite.git
    branch: master

- name: bosh-lite-lock
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-ci
    private_key: {{cf-cli-eng-github-private-key}}
    branch: locks
    pool: bosh-lites

- name: cli
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli
    private_key: {{cf-cli-eng-github-private-key}}
    branch: master
    paths:
    - ci

- name: cli-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-ci
    private_key: {{cf-cli-eng-github-private-key}}
    branch: master

- name: cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: master

jobs:
- name: deploy-boshlite-1
  serial: true
  plan:
  - put: bosh-lite-lock
    params:
      claim: {{lite-1-hostname}}
  - do:
    - aggregate:
      - get: cli-ci
      - get: cf-release
      - get: bosh-lite
      - get: cli
    - task: destroy
      file: cli/ci/tasks/destroy-cf-lite.yml
      config:
        params:
          AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
          AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
          AWS_REGION: {{lite-aws-region}}
          LITE_INSTANCE_NAME: bosh-lite-1
    - task: provision
      privileged: true
      file: cli/ci/tasks/provision-cf-lite.yml
      config:
        params:
          AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
          AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
          AWS_REGION: {{lite-aws-region}}
          AWS_SUBNET_ID: {{lite-aws-subnet-id}}
          AWS_SECURITY_GROUP: {{lite-aws-security-group}}
          LITE_NAME: {{lite-1-name}}
          LITE_KEYPAIR: {{lite-keypair}}
          LITE_HOSTNAME: {{lite-1-hostname}}
          LITE_PRIVATE_IP_ADDRESS: {{lite-1-private-ip-address}}
          LITE_PRIVATE_KEY_PATH: {{lite-private-key-path}}
    ensure:
      put: bosh-lite-lock
      params:
        release: bosh-lite-lock

- name: deploy-boshlite-2
  serial: true
  plan:
  - put: bosh-lite-lock
    params:
      claim: {{lite-2-hostname}}
  - do:
    - aggregate:
      - get: cli-ci
      - get: cf-release
      - get: bosh-lite
      - get: cli
    - task: destroy
      file: cli/ci/tasks/destroy-cf-lite.yml
      config:
        params:
          AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
          AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
          AWS_REGION: {{lite-aws-region}}
          LITE_INSTANCE_NAME: bosh-lite-2
    - task: provision
      privileged: true
      file: cli/ci/tasks/provision-cf-lite.yml
      config:
        params:
          AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
          AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
          AWS_REGION: {{lite-aws-region}}
          AWS_SUBNET_ID: {{lite-aws-subnet-id}}
          AWS_SECURITY_GROUP: {{lite-aws-security-group}}
          LITE_NAME: {{lite-2-name}}
          LITE_KEYPAIR: {{lite-keypair}}
          LITE_HOSTNAME: {{lite-2-hostname}}
          LITE_PRIVATE_IP_ADDRESS: {{lite-2-private-ip-address}}
          LITE_PRIVATE_KEY_PATH: {{lite-private-key-path}}
    ensure:
      put: bosh-lite-lock
      params:
        release: bosh-lite-lock

- name: deploy-boshlite-3
  serial: true
  plan:
  - put: bosh-lite-lock
    params:
      claim: {{lite-3-hostname}}
  - do:
    - aggregate:
      - get: cli-ci
      - get: cf-release
      - get: bosh-lite
      - get: cli
    - task: destroy
      file: cli/ci/tasks/destroy-cf-lite.yml
      config:
        params:
          AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
          AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
          AWS_REGION: {{lite-aws-region}}
          LITE_INSTANCE_NAME: bosh-lite-3
    - task: provision
      privileged: true
      file: cli/ci/tasks/provision-cf-lite.yml
      config:
        params:
          AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
          AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
          AWS_REGION: {{lite-aws-region}}
          AWS_SUBNET_ID: {{lite-aws-subnet-id}}
          AWS_SECURITY_GROUP: {{lite-aws-security-group}}
          LITE_NAME: {{lite-3-name}}
          LITE_KEYPAIR: {{lite-keypair}}
          LITE_HOSTNAME: {{lite-3-hostname}}
          LITE_PRIVATE_IP_ADDRESS: {{lite-3-private-ip-address}}
          LITE_PRIVATE_KEY_PATH: {{lite-private-key-path}}
    ensure:
      put: bosh-lite-lock
      params:
        release: bosh-lite-lock

- name: deploy-boshlite-4
  serial: true
  plan:
  - put: bosh-lite-lock
    params:
      claim: {{lite-4-hostname}}
  - do:
    - aggregate:
      - get: cli-ci
      - get: cf-release
      - get: bosh-lite
      - get: cli
    - task: destroy
      file: cli/ci/tasks/destroy-cf-lite.yml
      config:
        params:
          AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
          AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
          AWS_REGION: {{lite-aws-region}}
          LITE_INSTANCE_NAME: bosh-lite-4
    - task: provision
      privileged: true
      file: cli/ci/tasks/provision-cf-lite.yml
      config:
        params:
          AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
          AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
          AWS_REGION: {{lite-aws-region}}
          AWS_SUBNET_ID: {{lite-aws-subnet-id}}
          AWS_SECURITY_GROUP: {{lite-aws-security-group}}
          LITE_NAME: {{lite-4-name}}
          LITE_KEYPAIR: {{lite-keypair}}
          LITE_HOSTNAME: {{lite-4-hostname}}
          LITE_PRIVATE_IP_ADDRESS: {{lite-4-private-ip-address}}
          LITE_PRIVATE_KEY_PATH: {{lite-private-key-path}}
    ensure:
      put: bosh-lite-lock
      params:
        release: bosh-lite-lock

