---
resources:
- name: bosh-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-lite.git
    branch: master

- name: bosh-lites-acceptance-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: {{cli-pools-github-private-key}}
    branch: master
    pool: bosh-lites-acceptance

- name: cli
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli
    private_key: {{cf-cli-eng-github-private-key}}
    branch: master
    paths:
    - ci

- name: cli-private
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-private
    private_key: {{cf-cli-eng-github-private-key}}
    branch: master

- name: cf-release-repo
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: master

- name: diego-repo
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/diego-release.git
    branch: master

- name: cf-routing-release-repo
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/cf-routing-release.git
    branch: master

- name: cf-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-release

- name: etcd-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release

- name: garden-linux-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/garden-linux-release

- name: diego-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/diego-release

- name: cflinuxfs2-rootfs-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cflinuxfs2-rootfs-release

- name: cf-routing-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/cf-routing-release

- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: bosh-lite-deploy-cf
  type: bosh-deployment
  source:
    target: {{lite-acceptance-private-ip-address}}
    username: admin
    password: admin
    deployment: cf-warden

jobs:
- name: destroy-bosh-lite
  serial: true
  plan:
  - aggregate:
    - get: cli
    - put: bosh-lite-lock
      resource: bosh-lites-acceptance-pool
      params:
        claim: {{lite-acceptance-hostname}}
  - task: destroy
    file: cli/ci/tasks/destroy-cf-lite.yml
    params:
      AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
      AWS_REGION: {{lite-aws-region}}
      LITE_INSTANCE_NAME: {{lite-acceptance-name}}
    ensure:
      put: bosh-lites-acceptance-pool
      params:
        release: bosh-lite-lock

- name: provision-bosh-lite
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-acceptance-pool
      passed: [destroy-bosh-lite]
      trigger: true
    - get: cli-private
    - get: bosh-lite
    - get: cli
    - put: bosh-lite-lock
      resource: bosh-lites-acceptance-pool
      params:
        claim: {{lite-acceptance-hostname}}
  - task: provision
    file: cli/ci/tasks/provision-cf-lite.yml
    privileged: true
    params:
      AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
      LITE_KEYPAIR: {{acceptance-keypair}}
      LITE_PRIVATE_KEY_PATH: {{acceptance-private-key-path}}
      AWS_SECURITY_GROUP: {{lite-acceptance-security-group}}
      AWS_SUBNET_ID: {{lite-acceptance-subnet-id}}
      LITE_NAME: {{lite-acceptance-name}}
      LITE_PRIVATE_IP_ADDRESS: {{lite-acceptance-private-ip-address}}
  - task: associate-elastic-ip
    file: cli/ci/tasks/associate-elastic-ip.yml
    params:
      AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
      AWS_DEFAULT_REGION: {{lite-aws-region}}
      LITE_INSTANCE_NAME: {{lite-acceptance-name}}
      LITE_PUBLIC_IP_ADDRESS: {{lite-acceptance-public-ip}}
    ensure:
      put: bosh-lites-acceptance-pool
      params:
        release: bosh-lite-lock

- name: deploy-cf-release
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-acceptance-pool
      passed: [provision-bosh-lite]
      trigger: true
    - get: cli
    - get: cf-release-repo
    - get: cf-release
    - get: bosh-lite-stemcell
    - put: bosh-lite-lock
      resource: bosh-lites-acceptance-pool
      params:
        claim: {{lite-acceptance-hostname}}
  - task: create-cf-manifest
    file: cli/ci/tasks/create-bosh-lite-cf-manifest.yml
    params:
      LITE_PRIVATE_IP_ADDRESS: {{lite-acceptance-private-ip-address}}
      LITE_HOSTNAME: {{lite-acceptance-hostname}}
  - put: bosh-lite-deploy-cf
    params:
      manifest: bosh-lite-cf-manifest/cf.yml
      stemcells:
        - bosh-lite-stemcell/stemcell.tgz
      releases:
        - cf-release/release.tgz
    ensure:
      put: bosh-lites-acceptance-pool
      params:
        release: bosh-lite-lock

- name: smoke-test
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-acceptance-pool
      passed: [deploy-cf-release]
      trigger: true
    - get: cli
    - put: bosh-lite-lock
      resource: bosh-lites-acceptance-pool
      params:
        claim: {{lite-acceptance-hostname}}
  - task: run-smoke-tests
    file: cli/ci/tasks/run-smoke-tests.yml
    params:
      LITE_PRIVATE_IP_ADDRESS: {{lite-acceptance-private-ip-address}}
    ensure:
      put: bosh-lites-acceptance-pool
      params:
        release: bosh-lite-lock

- name: deploy-diego-release
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-acceptance-pool
      passed: [smoke-test]
      trigger: true
    - put: bosh-lite-lock
      resource: bosh-lites-acceptance-pool
      params:
        claim: {{lite-acceptance-hostname}}
    - get: etcd-release
    - get: garden-linux-release
    - get: diego-release
    - get: diego-repo
    - get: cflinuxfs2-rootfs-release
    - get: cli
  - task: deploy-diego
    file: cli/ci/tasks/deploy-diego.yml
    params:
      LITE_PRIVATE_IP_ADDRESS: {{lite-acceptance-private-ip-address}}
    ensure:
      put: bosh-lites-acceptance-pool
      params:
        release: bosh-lite-lock

- name: deploy-routing-release
  serial: true
  plan:
  - aggregate:
    - get: bosh-lites-acceptance-pool
      passed: [deploy-diego-release]
      trigger: true
    - put: bosh-lite-lock
      resource: bosh-lites-acceptance-pool
      params:
        claim: {{lite-acceptance-hostname}}
    - get: cf-routing-release
    - get: cf-routing-release-repo
    - get: cf-release-repo
    - get: cli
  - task: deploy-routing
    file: cli/ci/tasks/deploy-routing.yml
    params:
      LITE_PRIVATE_IP_ADDRESS: {{lite-acceptance-private-ip-address}}
      LITE_HOSTNAME: {{lite-acceptance-hostname}}
  - task: test-routing
    file: cli/ci/tasks/test-routing.yml
    params:
      LITE_PRIVATE_IP_ADDRESS: {{lite-acceptance-private-ip-address}}
    ensure:
      put: bosh-lites-acceptance-pool
      params:
        release: bosh-lite-lock
