---
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego?/temporary_local_tps
  value: true
- type: replace
  path: /instance_groups/-
  value:
    name: isolated-diego-cell-1
    azs:
    - z1
    instances: 1
    vm_type: r3.xlarge
    vm_extensions:
    - 100GB_ephemeral_disk
    stemcell: default
    networks:
    - name: private
    jobs:
    - name: consul_agent
      release: consul
      consumes:
        consul: {from: consul_server}
    - name: cflinuxfs2-rootfs-setup
      release: cflinuxfs2-rootfs
    - name: garden
      release: garden-runc
      properties:
        garden:
          default_container_grace_time: 0
          destroy_containers_on_start: true
          graph_cleanup_threshold_in_mb: 0
          deny_networks:
          - 0.0.0.0/0
          persistent_image_list:
          - "/var/vcap/packages/cflinuxfs2/rootfs"
    - name: rep
      release: diego
      properties:
        diego:
          executor:
            ca_certs_for_downloads: "((blobstore_tls.ca))"
          rep:
            bbs:
              ca_cert: "((diego_bbs_client.ca))"
              client_cert: "((diego_bbs_client.certificate))"
              client_key: "((diego_bbs_client.private_key))"
            preloaded_rootfses:
            - cflinuxfs2:/var/vcap/packages/cflinuxfs2/rootfs
            placement_tags:
            - isolated-1
            require_tls: true
            ca_cert: "((diego_rep_server.ca))"
            server_cert: "((diego_rep_server.certificate))"
            server_key: "((diego_rep_server.private_key))"
          ssl:
            skip_cert_verify: true
    - name: metron_agent
      release: loggregator
      properties:
        syslog_daemon_config:
          enable: false
        metron_agent:
          deployment: "((system_domain))"
          etcd:
            client_cert: "((etcd_client.certificate))"
            client_key: "((etcd_client.private_key))"
        metron_endpoint:
          shared_secret: "((dropsonde_shared_secret))"
        loggregator:
          tls:
            ca_cert: "((loggregator_tls_metron.ca))"
            metron:
              cert: "((loggregator_tls_metron.certificate))"
              key: "((loggregator_tls_metron.private_key))"
          etcd:
            require_ssl: true
            ca_cert: "((etcd_server.ca))"
            machines:
            - cf-etcd.service.cf.internal
