resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
  - name: cron
    type: docker-image
    source:
      repository: cftoolsmiths/cron-test

resources:
  - name: mail
    type: email
    source:
      smtp:
        host: "smtp.sendgrid.net"
        port: "2525"
        password: {{sendgrid_password}}
        username: {{sendgrid_username}}
      from: cf-cli-eng@pivotal.io
      to:
        - ask@pivotal.io
        - mboedicker@pivotal.io
        - nwei@pivotal.io
  - name: weekly-trigger
    type: cron
    source:
      expression: "0 9 * * 2"
      location: "America/Los_Angeles"
  - name: subject
    type: s3
    source:
      bucket: cf-cli-cheez
      versioned_file: subject
  - name: body
    type: s3
    source:
      bucket: cf-cli-cheez
      versioned_file: body

jobs:
- name: send-email
  plan:
    - aggregate:
      - get: weekly-trigger
        trigger: true
      - get: subject
      - get: body
    - put: mail
      params:
        subject: subject/subject
        body: body/body
