---
resource_types:
# TODO: remove temp tracker resource when https://github.com/concourse/tracker-resource/issues/17 is fixed
- name: tracker-resource-fixed
  type: docker-image
  source:
    repository: concourse/tracker-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    ignore_paths:
    - ci
    - integration

- name: cli-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths:
    - bin
    - ci

- name: cli-integration
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths:
    - integration

- name: cf-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-acceptance-tests
    branch: owned-by-cf-cli

- name: cf-cli-binaries
  type: s3
  source:
    bucket: {{staging-bucket-name}}
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: cf-cli-binaries.tgz

- name: edge-linux-binary-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli_edge_linux_i686.tgz
    region_name: us-west-1

- name: edge-linux-binary-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli_edge_linux_x86-64.tgz
    region_name: us-west-1

- name: edge-osx-binary-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli_edge_osx.tgz
    region_name: us-west-1

- name: edge-windows-binary-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli_edge_win32.zip
    region_name: us-west-1

- name: edge-windows-binary-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli_edge_winx64.zip
    region_name: us-west-1

- name: edge-deb-installer-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_i686.deb
    region_name: us-west-1

- name: edge-deb-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_x86-64.deb
    region_name: us-west-1

- name: edge-redhat-installer-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_i686.rpm
    region_name: us-west-1

- name: edge-redhat-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_x86-64.rpm
    region_name: us-west-1

- name: edge-osx-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_osx.pkg
    region_name: us-west-1

- name: edge-windows-installer-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_win32.zip
    region_name: us-west-1

- name: edge-windows-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_winx64.zip
    region_name: us-west-1

- name: bosh-lites-dea-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: {{cli-pools-github-private-key}}
    branch: master
    pool: bosh-lites-dea

- name: hardknox-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: {{cli-pools-github-private-key}}
    branch: master
    pool: bosh-lites-diego

# TODO: remove temp tracker resource when https://github.com/concourse/tracker-resource/issues/17 is fixed
- name: cf-cli-tracker
  type: tracker-resource-fixed
  source:
    token: {{cf-cli-public-tracker-token}}
    project_id: {{cf-cli-public-tracker-project-id}}
    tracker_url: https://www.pivotaltracker.com

- name: golang
  type: docker-image
  source:
    repository: golang
    tag: latest

- name: cli-ci-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths: [ci/Dockerfile]

- name: cf-cli-image
  type: docker-image
  source:
    repository: cloudfoundry/cli-ci
    username: {{dockerhub-username}}
    email: {{dockerhub-email}}
    password: {{dockerhub-password}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

- name: vars-store
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-private
    private_key: {{cli-private-github-private-key-write}}
    branch: master

groups:
- name: cli
  jobs:
  - units
  - build-binaries
  - integration
  - cats-diego
  - cats-linux
  - cats-windows
  - create-installers
- name: images
  jobs:
  - create-cli-ci-image

jobs:
- name: units
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      depth: 3
    - get: cli-ci
      depth: 3
  - aggregate:
    - task: units-linux
      file: cli-ci/ci/cli/tasks/units-linux.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-firehose'
           text: "linux unit tests failed :("
    - task: units-osx
      file: cli-ci/ci/cli/tasks/units-osx.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-firehose'
           text: "osx unit tests failed :("
    - task: units-windows
      file: cli-ci/ci/cli/tasks/units-windows.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-firehose'
           text: "windows unit tests failed :("
    - task: lint
      file: cli-ci/ci/cli/tasks/lint.yml

- name: build-binaries
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [units]
      depth: 3
    - get: cli-ci
      depth: 3
  - aggregate:
    - task: build
      file: cli-ci/ci/cli/tasks/build-binaries.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-firehose'
           text: "build binaries failed :("
    - task: build-osx
      file: cli-ci/ci/cli/tasks/build-osx-binary.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-firehose'
           text: "build osx binaries failed :("
  - task: combine-binaries
    file: cli-ci/ci/cli/tasks/combine-binaries.yml
  - put: cf-cli-binaries
    params:
      file: compiled/cf-cli-binaries.tgz

- name: integration
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [build-binaries]
      depth: 3
    - get: cf-cli-binaries
      passed: [build-binaries]
    - get: cli-ci
      depth: 3
    - get: cli-integration
      depth: 3
    - get: vars-store
    - put: bosh-lite-lock
      resource: hardknox-pool
      params:
        acquire: true
  - do:
    - task: cleanup-integration
      file: cli-ci/ci/cli/tasks/cleanup-integration.yml
    - task: integration-windows
      file: cli-ci/ci/cli/tasks/integration-windows.yml
      input_mapping:
        cf-credentials: cleanup-integration-outputs
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-firehose'
          text: "windows integration failed :("
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli/tasks/cleanup-integration.yml
    - task: integration-linux
      file: cli-ci/ci/cli/tasks/integration-linux.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-firehose'
          text: "linux integration failed :("
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli/tasks/cleanup-integration.yml
  on_failure:
    put: hardknox-pool
    params:
      release: bosh-lite-lock

- name: cats-diego
  serial: true
  plan:
  - aggregate:
    - get: cli
      passed: [integration]
      depth: 3
    - get: cf-acceptance-tests
    - get: cf-cli-binaries
      passed: [integration]
    - get: cli-ci
      depth: 3
    - get: vars-store
    - get: bosh-lite-lock
      trigger: true
      passed: [integration]
      resource: hardknox-pool
  - do:
    - task: cats-config
      file: cli-ci/ci/cli/tasks/cats-config-diego.yml
      params:
        INCLUDE_V3: false
        BROKER_START_TIMEOUT: 330
        CF_PUSH_TIMEOUT: 210
        DEFAULT_TIMEOUT: 60
        LONG_CURL_TIMEOUT: 210
    - task: cats
      file: cli-ci/ci/cli/tasks/cats-linux.yml
      params:
        BACKEND: diego
        NODES: 16
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-firehose'
          text: "cats diego failed :("
      ensure:
        put: hardknox-pool
        params:
          release: bosh-lite-lock

- name: cats-linux
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [build-binaries]
      depth: 3
    - get: cf-acceptance-tests
    - get: cf-cli-binaries
      passed: [build-binaries]
    - get: cli-ci
      depth: 3
    - put: bosh-lite-lock
      resource: bosh-lites-dea-pool
      params:
        acquire: true
  - do:
    - task: cats-config
      file: cli-ci/ci/cli/tasks/cats-config.yml
      params:
        BACKEND: dea
        INCLUDE_V3: false
        BROKER_START_TIMEOUT: 330
        CF_PUSH_TIMEOUT: 210
        DEFAULT_TIMEOUT: 60
        LONG_CURL_TIMEOUT: 210
    - task: cats
      file: cli-ci/ci/cli/tasks/cats-linux.yml
      params:
        BACKEND: dea
        NODES: 10
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-firehose'
          text: "cats linux failed :("
      ensure:
        put: bosh-lites-dea-pool
        params:
          release: bosh-lite-lock

- name: cats-windows
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [build-binaries]
      depth: 3
    - get: cf-cli-binaries
      passed: [build-binaries]
    - get: cf-acceptance-tests
    - get: cli-ci
      depth: 3
    - put: bosh-lite-lock
      resource: bosh-lites-dea-pool
      params:
        acquire: true
  - do:
    - task: cats-config
      file: cli-ci/ci/cli/tasks/cats-config.yml
      params:
        BACKEND: dea
        INCLUDE_V3: false
        BROKER_START_TIMEOUT: 330
        CF_PUSH_TIMEOUT: 210
        DEFAULT_TIMEOUT: 60
        LONG_CURL_TIMEOUT: 210
    - task: cats
      file: cli-ci/ci/cli/tasks/cats-windows.yml
      params:
        NODES: 10
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-firehose'
           text: "cats windows failed :("
      ensure:
        put: bosh-lites-dea-pool
        params:
          release: bosh-lite-lock

- name: create-installers
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [cats-linux, cats-windows, cats-diego]
      depth: 3
    - get: cf-cli-binaries
      passed: [cats-linux, cats-windows, cats-diego]
    - get: cli-ci
      depth: 3
  - task: extract-binaries
    file: cli-ci/ci/cli/tasks/extract-binaries.yml
    on_failure:
       put: slack-alert
       params:
         channel: '#cli-firehose'
         text: "extracting the binaries in installer creation failed :("
  - aggregate:
    - task: unix
      file: cli-ci/ci/cli/tasks/create-installers.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-firehose'
           text: "create unix installers failed :("
    - task: windows
      file: cli-ci/ci/cli/tasks/create-installers-windows.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-firehose'
           text: "create windows installer failed :("
  - task: package-binaries
    file: cli-ci/ci/cli/tasks/package-binaries.yml
    on_failure:
       put: slack-alert
       params:
         channel: '#cli-firehose'
         text: "extracting the binaries in installer creation failed :("
  - aggregate:
    - put: edge-linux-binary-32
      params:
        file: archives/cf-cli_edge_linux_i686.tgz
    - put: edge-linux-binary-64
      params:
        file: archives/cf-cli_edge_linux_x86-64.tgz
    - put: edge-osx-binary-64
      params:
        file: archives/cf-cli_edge_osx.tgz
    - put: edge-windows-binary-32
      params:
        file: archives/cf-cli_edge_win32.zip
    - put: edge-windows-binary-64
      params:
        file: archives/cf-cli_edge_winx64.zip
    - put: edge-deb-installer-32
      params:
        file: archives/cf-cli-installer_i686.deb
    - put: edge-deb-installer-64
      params:
        file: archives/cf-cli-installer_x86-64.deb
    - put: edge-redhat-installer-32
      params:
        file: archives/cf-cli-installer_i686.rpm
    - put: edge-redhat-installer-64
      params:
        file: archives/cf-cli-installer_x86-64.rpm
    - put: edge-osx-installer-64
      params:
        file: archives/cf-cli-installer_osx.pkg
    - put: edge-windows-installer-32
      params:
        file: winstallers/cf-cli-installer_win32.zip
    - put: edge-windows-installer-64
      params:
        file: winstallers/cf-cli-installer_winx64.zip
    # TODO: remove temp tracker resource when https://github.com/concourse/tracker-resource/issues/17 is fixed
    - put: cf-cli-tracker
      params:
        repos:
        - cli

- name: create-cli-ci-image
  serial: true
  plan:
  - aggregate:
    - get: cli-ci-dockerfile
      trigger: true
      depth: 3
    - get: golang
      trigger: true
      params: {save: true}
  - put: cf-cli-image
    params:
      load_base: golang
      build: cli-ci-dockerfile/ci
