
---
platform: linux
image: docker:///cloudfoundry/cli-ci

inputs:
  - name: bosh-lite-lock

outputs:
  - name: cats-config

params:
  BACKEND:
  INCLUDE_V3:
  BROKER_START_TIMEOUT:
  CF_PUSH_TIMEOUT:
  DEFAULT_TIMEOUT:
  LONG_CURL_TIMEOUT:

run:
  path: bash
  args:
  - -c
  - |
    set -eux

    export DOMAIN=`cat bosh-lite-lock/name`

    if [[ $BACKEND == "diego" ]]; then
      export IS_DIEGO_ENABLED=true
    else
      export IS_DIEGO_ENABLED=false
    fi

    cat << EOF | jq -S . > cats-config/integration_config.json
    {
      "admin_password": "admin",
      "admin_user": "admin",
      "api": "api.$DOMAIN",
      "apps_domain": "$DOMAIN",
      "backend" : "$BACKEND",
      "broker_start_timeout": $BROKER_START_TIMEOUT,
      "cf_push_timeout": $CF_PUSH_TIMEOUT,
      "default_timeout": $DEFAULT_TIMEOUT,
      "long_curl_timeout": $LONG_CURL_TIMEOUT,
      "skip_ssl_validation": true,
      "use_http": false,
      "include_v3": $INCLUDE_V3,
      "include_apps": true,
      "include_backend_compatibility": true,
      "include_detect": true,
      "include_docker": $IS_DIEGO_ENABLED,
      "include_internet_dependent": true,
      "include_privileged_container_support": false,
      "include_route_services": true,
      "include_routing": true,
      "include_zipkin": false,
      "include_security_groups": true,
      "include_services": true,
      "include_ssh": $IS_DIEGO_ENABLED,
      "include_sso": false,
      "include_tasks": false
    }
    EOF
