---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: bosh-lite-lock
  - name: vars-store

outputs:
  - name: cats-config

params:
  INCLUDE_V3:
  BROKER_START_TIMEOUT:
  CF_PUSH_TIMEOUT:
  DEFAULT_TIMEOUT:
  LONG_CURL_TIMEOUT:

run:
  path: bash
  args:
  - -c
  - |
    set -eux

    DOMAIN=`cat bosh-lite-lock/name`

    CF_PASSWORD=$(bosh int vars-store/ci/infrastructure/hardknox/deployment-vars.yml --path /uaa_scim_users_admin_password)

    cat << EOF | jq -S . > cats-config/integration_config.json
    {
      "admin_password": "$CF_PASSWORD",
      "admin_user": "admin",
      "api": "api.$DOMAIN",
      "apps_domain": "$DOMAIN",
      "backend" : "diego",
      "broker_start_timeout": $BROKER_START_TIMEOUT,
      "cf_push_timeout": $CF_PUSH_TIMEOUT,
      "default_timeout": $DEFAULT_TIMEOUT,
      "long_curl_timeout": $LONG_CURL_TIMEOUT,
      "skip_ssl_validation": true,
      "use_http": false,
      "include_v3": $INCLUDE_V3,
      "include_apps": true,
      "include_backend_compatibility": false,
      "include_detect": true,
      "include_docker": true,
      "include_internet_dependent": true,
      "include_privileged_container_support": false,
      "include_route_services": true,
      "include_routing": true,
      "include_zipkin": false,
      "include_security_groups": true,
      "include_services": true,
      "include_ssh": true,
      "include_sso": false,
      "include_tasks": false
    }
    EOF
