---
platform: linux
image: docker:///cloudfoundry/cli-ci

inputs:
- name: cli-ci
- name: cf-cli-binaries
- name: bosh-lite-lock
- name: vars-store

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    domain=$(cat bosh-lite-lock/name)
    api_endpoint="https://api.${domain}"
    password=$(bosh2 int vars-store/ci/infrastructure/hardknox/deployment-vars.yml --path /uaa_scim_users_admin_password)

    export PATH=$GOPATH/bin:$PATH

    pushd cf-cli-binaries
      tar xvzf cf-cli-binaries.tgz
      chmod +x cf-cli_linux_x86-64
      mv cf-cli_linux_x86-64 $GOPATH/bin/cf
    popd

    cd cli-ci
    CF_API=${api_endpoint} CF_PASSWORD=${password} bin/cleanup-integration
