---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: cli-ci
- name: cf-cli-binaries
- name: bosh-lite-lock
- name: vars-store

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export DOMAIN=$(cat bosh-lite-lock/name)
    export API_ENDPOINT="https://api.${DOMAIN}"
    export CF_PASSWORD=$(bosh int vars-store/ci/infrastructure/hardknox/deployment-vars.yml --path /uaa_scim_users_admin_password)

    export PATH=$GOPATH/bin:$PATH

    pushd cf-cli-binaries
      tar xvzf cf-cli-binaries.tgz
      chmod +x cf-cli_linux_x86-64
      mv cf-cli_linux_x86-64 $GOPATH/bin/cf
    popd

    cd cli-ci
    CF_API=$API_ENDPOINT bin/cleanup-integration
