---
platform: linux
image: docker:///cloudfoundry/cli-ci

inputs:
- name: cross-compiled
- name: signed
- name: osx-compiled

outputs:
- name: compiled

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cwd=$PWD

    mkdir combined

    pushd cross-compiled
      tar -xzf *.tgz
      rm *.tgz
      mv * $cwd/combined
    popd

    pushd signed
      mv * $cwd/combined
      chmod 0755 $cwd/combined/cf-cli_win*
    popd

    pushd osx-compiled
      tar -xzf *.tgz
      rm *.tgz
      mv * $cwd/combined
    popd

    cd $cwd/combined
    tar -cvzf $cwd/compiled/cf-cli-binaries.tgz *
