platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cli-i18n

outputs:
- name: i18n-data

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cwd=$PWD

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    go version
    ./cli-i18n/bin/generate-language-resources

    mv ./cli-i18n/resources/i18n_resources.go i18n-data
