---
platform: linux
image: docker:///cloudfoundry/cli-ci

inputs:
- name: cli
  path: gopath/src/github.com/cloudfoundry/cli

params:
  LINT_SLOW: true
  LINT_DEADLINE: 30s
  LINT_SLOW_DEADLINE: 5m

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    cd $GOPATH/src/github.com/cloudfoundry/cli

    bin/lint
