platform: linux
image: docker:///cloudfoundry/cli-ci

inputs:
- name: final-cli
  path: cli
- name: cli-private
- name: cli
  path: gopath/src/github.com/cloudfoundry/cli
- name: cf-cli-installers

params:
  GPG_KEY:
  KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_ACCESS_KEY_ID:
  AWS_BUCKET_NAME: cf-cli-debian

run:
  path: bash
  args:
  - -c
  - |
    set -ex
    gpg --import <(echo "${GPG_KEY}")
    export DEBIAN_FRONTEND=noninteractive

    mkdir installers

    pushd cli
      git remote set-url origin https://github.com/cloudfoundry/cli.git
      git fetch --tags
      release_tag=$( git show-ref --tags -d | grep $(git rev-parse HEAD) | cut -d'/' -f3 | egrep 'v[0-9]' | cut -d'v' -f2 )
    popd

    if [ -z "${release_tag}" ]; then
      echo "Expected the commit that triggered this build to be tagged." >&2
      exit 1
    fi

    tar -xvzf cf-cli-installers/cf-cli-installers.tgz -C installers

    filename_regex="cf-cli(-installer)?([-_0-9a-z]+)?(\.[a-z]+)?"
    pushd installers
      for installer in *.deb; do
        [[ "${installer}" =~ $filename_regex ]]
        os_arch="${BASH_REMATCH[2]}"
        mv "${installer}" "cf-cli-installer_${release_tag}${os_arch}.deb"
      done
    popd

    cat >> $HOME/.gnupg/gpg.conf <<EOF
personal-digest-preferences SHA256
cert-digest-algo SHA256
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
EOF

    deb-s3 upload installers/*.deb --preserve-versions --sign=${KEY_ID} --bucket=${AWS_BUCKET_NAME}

