platform: linux
image: docker:///cloudfoundry/cli-ci

inputs:
- name: cli-private
- name: cli
  path: gopath/src/github.com/cloudfoundry/cli
- name: cf-cli-installers

params:
  GPG_KEY:
  KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_ACCESS_KEY_ID:
  AWS_BUCKET_NAME: cf-cli-debian

run:
  path: bash
  args:
  - -c
  - |
    set -ex
    gpg --import ./cli-private/ci/gpg_key/gpg.key
    export DEBIAN_FRONTEND=noninteractive
    apt-get -y install ruby1.9.1
    gem install deb-s3

    mkdir installers
    tar -xvzf cf-cli-installers/cf-cli-installers.tgz -C installers
    deb-s3 upload installers/*.deb -p --sign=${KEY_ID} -b ${AWS_BUCKET_NAME}

