---
platform: darwin

inputs:
- name: cli
  path: gopath/src/code.cloudfoundry.org/cli

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    cd $GOPATH/src/code.cloudfoundry.org/cli

    export LC_ALL="en_US.UTF-8"

    pushd vendor/github.com/onsi/ginkgo/ginkgo
    go install
    popd

    go version
    ginkgo version

    echo -e "\n Vetting packages for potential issues..."
    go tool vet -all -shadow=true ./api ./actor ./command ./integration ./types ./util ./version
    CF_HOME=$(pwd)/fixtures ginkgo -r -randomizeAllSpecs -randomizeSuites -skipPackage -race integration
